### ISSUE TITLE
Create alternate front wheel

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#13]
We’d like to try adapted versions of the wheel to attach directly to the bearing and motor.

The track used will be [this](https://es.aliexpress.com/item/32921129749.html)

The task is to create two versions of [this part](https://www.thingiverse.com/thing:4737213) a front version and a back version. 

The front-wheel will have the features in the images below. 

![inner](https://user-images.githubusercontent.com/400875/155848094-53b33b81-7295-4844-96a2-59bb193b6573.jpeg)
![image3](https://user-images.githubusercontent.com/400875/155848106-a47bed3b-030d-4dd7-8f2f-6a6ff27b070a.jpeg)
![image (2)](https://user-images.githubusercontent.com/400875/155848119-4e24a717-ca3b-4b91-81d6-ebf65b4a408f.jpg)
![image (1)](https://user-images.githubusercontent.com/400875/155848133-4ece879a-3826-4a5b-a4e7-c9aa435edf72.jpg)

The bearing pin will screw to the robot body.

**Comment by runger1101001** [comment]
Note that I already have fusion files for the above if anyone needs.
I'm also working on getting something that looks like Rosmo in a form that I can print and build it.

**Comment by runger1101001** [comment]
I think it would be good to find some better tracks. I know lego is nice because available and standardised, but even many lego models use rubber tracks. This is because the linked lego tracks are much too weak in practice. They can work well in a stationary device of some kind, but as robot tracks they are too weak. Depending on the robots weight and the motor's power, even just normal acceleration can pull them apart, and on carpet the shear-forces of any kind of turn have a tendency to pull them apart.
I think we should find some suitable rubber/nylon/silicon tracks and then design the wheels for those.

**Comment by samuk** [comment]
> Note that I already have fusion files for the above if anyone needs.

Ah great, I didn't realise that. Could you stick them [here](https://github.com/rosmo-robot/Rosmo_3D/tree/main/v1_optional_tracks)? I think @aard may be up for having a go at the lego one.

I take your point on rubber tracks, I'll have a look and see if I can find any.

These [TPU printed ones](https://www.thingiverse.com/thing:3653785) might be [viable](https://www.youtube.com/watch?v=jxZkj3Deqsw&t=13s)

**Comment by samuk** [comment]
I wonder if this would work:https://www.robotdigg.com/product/375

The distance from the centre of wheels on the current model is 6.5 cm

Using 4cm wheels this gives a track length of ~29cm

**Comment by runger1101001** [comment]
:-) I've ordered belts from robotdigg before... they have a lot of different ones... maybe a v-shaped one could work. But maybe something that is supposed to be a track would work even better

Printing them in TPU could work. It's not the most forgiving 3D printing material, but I have printed a bunch of tires and tracks in Ninjaflex (TPU) and they come out pretty well. There is a lot of stringing and the material is impossible to sand and very hard to cut because its so flexy. As long as there are no fine structures you can get pretty decent results. The pics on thingyverse are quite accurate for what you can expect.

Tracks could also be tensioned by a third, higher up wheel, but of course that adds more cost in the form of 2 extra bearings...

I'll search around a bit more. I found some model tank tracks on AliExpress, but they looked a bit dubious.

**Comment by runger1101001** [comment]
These are pretty cool, but of course a bit expensive: https://www.gobilda.com/badlands-tank-track-24mm-pitch-112mm-width-rubber-tread-6-pack/

These use pins like a wrist-watch:
https://toykidmama.com/doit-plastic-track-for-damping-robotic-smart-car-model-chain-for-tracked-vehicle-clawler-track-type-tank-accessory-diy-rc-toy-3952skn2

A compendium of home-made tracks:
https://www.intorobotics.com/inspiration-diy-tank-treads-collection/

**Comment by samuk** [comment]
The 4cm wide Bilda & 10cm wide pins ones are both a bit wide?

From the homemade list these look pretty interesting:https://www.thingiverse.com/thing:39253 I wonder if we could find a good solution for the pins?

**Comment by runger1101001** [comment]
Those pins are definitely not FDM printable...

**Comment by samuk** [comment]
Sure, I was thinking something along the lines of [these pins](https://www.aliexpress.com/item/4000309875370.html), maybe M1.5 if we can find them?

I wonder if we could 3dprint & pin something compatible with the nice-but-expensive [Tamiya Track](https://www.tamiya.com/japan/products/70237/index.html) It's available in [UK](https://www.rcjaz.co.uk/tamiya-70237-link-type-track-sprocket-set-p-18901.html) as used on  [this cute bot](https://twitter.com/neet2121/status/1497918138260033536/photo/1)?

**Comment by samuk** [comment]
Please see https://github.com/rosmo-robot/Rosmo_3D/new/main/V2
