### ISSUE TITLE
Rosmo design guidelines & colour palette(s)

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#7]
**Features to include somewhere on PCB silkscreen**
[Open hardware logo](https://www.oshwa.org/open-source-hardware-logo/)
Licence: https://ohwr.org/cern_ohl_p_v2.txt
https://rosmo.io
Copyright: Primary author name - year
Version number V1.X

Anyone can make any of these bits in any colour they choose. In terms of the colours we use for bits, we produce & put on the website/social media I propose.

**'Default' colours - White/Red/Black** 
White solder mask. Black silkscreen 
White robot body
White cases.
Black lego wheels.
Red [Face](https://github.com/rosmo-robot/Rosmo_3D/issues/6)
(Will also look good with [official M5 in white](https://shop.m5stack.com/collections/stack-series/products/m5stack-core2-esp32-iot-development-kit?variant=35960244109476) or [red](https://shop.m5stack.com/collections/stack-series/products/m5stack-fire-iot-development-kit-psram-v2-6?variant=40494762918060))

**Pink colour**
White solder mask. Black silkscreen
Pink robot body
Pink cases.
Black lego wheels.
Pink [Face](https://github.com/rosmo-robot/Rosmo_3D/issues/6)

**Black/Yellow colours**
White solder mask. Black silkscreen
Black robot body
Black cases.
Yellow lego wheels.
Yellow [Face](https://github.com/rosmo-robot/Rosmo_3D/issues/6)
(Will also look good with official M5 in [black](https://shop.m5stack.com/collections/stack-series/products/esp32-basic-core-iot-development-kit-v2-6?variant=40724625064108) or [yellow](https://shop.m5stack.com/collections/stack-series/products/m5stack-core2-esp32-iot-development-kit-for-aws-iot-edukit))

**Comment by runger1101001** [comment]
Ouch, one day late on this issue...

Hmmmm....  do you mean red solder mask, white silk screen? The PCB colour itself is not really choosable, FR4 is a kind of dull yellow/khaki colour, and copper is copper. Plating can be tin or gold (ENIG), I think I went for tin to keep the costs down.

Red solder mask would be available, but adds 2 days to fabrication time because it is less commonly ordered, I presume.

At the moment I have ordered the board in white solder mask, black silk screen, because that's what the other m5 modules generally seem to use. If you care strongly about the colour of the prototypes I can ask the service rep to change the order, but I'd prefer not to. The v2 board shall be red, now that I know. :-)

**Comment by samuk** [comment]
Cool, all good :) Yes, I meant the other way around.( I shouldn't comment before coffee in the mornings..) I've edited my original comment.

Let's standardise on White PCB black silk, I don't feel strongly about it.

Do we have a version number, Open hardware logo & rosmo.io URL on the boards ordered?

**Comment by runger1101001** [comment]
Logo yes, the other two no... but I will add them now so the next boards have them.

**Comment by samuk** [comment]
Can still link to closed issues
